### ISSUE TITLE
Mantis runs are being labelled as RSA runs in database

### ISSUE THREAD

**Issue by ldeviveiros** [project8/dripline#130]
The Mantis runs are being labeled as with the daq_id for the RSA (daq_id=4) in the database.  This is because the daq_id is defined in run_table_db_interface.yaml, which both the RSA and Mantis use.  The value for daq_id should be defined in mantis_interface.yaml and RSA_interface.xml, so that you can have distinct values of daq_id even if you are running both at the same time.

**Comment by laroque** [comment]
@ldeviveiros I see you assigned yourself, have you already taken care of this? If not it is a one-line fix on the python side adding `daq_id = self.daq_name,` to the payload for the `run_name.setter` property.

The reason it isn't in is that I was waiting for the database to be updated so that one could do the insert using the daq_name rather than needing to have the int for each. That wasn't working some months ago when I wrote the daq interface.

The mantis and RSA service config files should already have the configurations we need. We just need to move the daq_id in the run_table_db_interface out of the "default" section (where if missing the default value is used) and into the required section (where an error is returned if it isn't provided).

**Comment by guiguem** [comment]
Has this issue been solved? We are not using Mantis anymore, btw...

**Comment by guiguem** [comment]
Mantis has been removed from the daq_run_interface.py.
