### ISSUE TITLE
numerous tests fail in python dripline interface due to bad mocking

### ISSUE THREAD

**Issue by kofron** [project8/dripline#35]
many tests are failing in the python dripline interface due to Node needing to get mocked up.

**Comment by laroque** [comment]
"Node" is a deprecated abstraction and has been refactored into "Portal" (though partially into "Service" and possibly other places also).

I'm closing this with wontfix because I believe we need to move to something more like end-to-end tests that use mocking for instruments, but which require testing against an active AMQP broker. This is because a large fraction of the bugs that should be caught depend on interactions with running services and communication through AMQP.
