### ISSUE TITLE
implement exceptions

### ISSUE THREAD

**Issue by laroque** [project8/dripline#69]
Messages have a field for exceptions which is entirely unused. We should define what those exceptions should look like, I propose we do something similar to HTML, using 3 digits where the 1st digit describes a meaningful subset of conditions.

Perhaps:

0-99: Success (and warnings?)
  * 0: the default success

100-199: AMQP related issues
 * 100: generic AMQP interaction error
 * 101: unable to connect to broker
 * 102: routing key not found

200-299: hardware related issues
 * 200: generic hardware interaction error
 * 201: unable to connect to device/device not found
 * 202: no response from instrument/timeout

300-399: consumer/provider/endpoint internal issues
 * 300: generic
 * 301: message encoding not indicated (is this a warning, should I guess)
 * 302: message decoding failed
 * 303: payload not well formed (for example, too many or too few arguments provided)
 * 304: invalid value (wrong value type or value out of range... should these be separate)

**Comment by nsoblath** [comment]
It would also be good to have a standard return message field in the payload.  This would 've optional and contain a human-readable message about the return status.

**Comment by nsoblath** [comment]
As of Mantis commit 12e69f9 in the amqp branch, Mantis now preliminarily supports returning error/success codes.

I suggest that we change the name of this field from "exception" to something else, since it can indicate success as well, and exceptions are typically bad.  As currently implemented in Mantis the field is "retcode."

I also have a return message in the payload that's always called "return-msg."

**Comment by laroque** [comment]
These exceptions with retcodes are now implemented in core/exceptions. The Endpoint.handle_request() method now catches on DriplineException (from which all of the above inherit) and will update the return code and payload message.
