### ISSUE TITLE
Add sender_info field to AMQP messages

### ISSUE THREAD

**Issue by nsoblath** [project8/dripline#72]
Suggested structure:
```json
"sender_info" :
{
    "package" : "mantis",
    "exe": "bin/mantis_client",
    "version": "2.5.5",
    "commit": "203985u..."
}
```

Related to Mantis issue project8/mantis#39

**Comment by laroque** [comment]
in setup.py, one could do something like:

```
verstr = "none"
try:
    verstr = open("VERSION").read().strip().replace(' ', '.')
    import subprocess
    verstr = subprocess.check_output(['git','describe','--long']).strip()
except <whatever>:
    <something>
```

then in __init__.py
```
import pkg_resources
__version__ = pkg_resources.require("dripline")[0].version.split('-')[0]
__commit__ = pkg_resources.require("dripline")[0].version.split('-')[-1]
```

I'm holding off for the moment to ponder just how badly that could fail.

**Comment by laroque** [comment]
A few clarifying questions:
1) Should exe be the name of the executable, or the path to it? If the latter I think it should always be an absolute path, since relative paths aren't useful without knowing the value of the working directory.
2) Should the hostname be included as an additional field? If not then the above path is again not so useful. In python this is easy to automate with:
```
import socket
socket.gethostname()
```
3) Should the local username be included? If we decide to implement a system lock (so that nobody changes the trap settings on you while you're trying to take data, for example) then this field could be one way to authenticate that... obviously it would be easily faked, but we're not dealing with malicious users here. In python:
```
import os
import pwd
pwd.getpwuid(os.getuid())[0]
```

**Comment by nsoblath** [comment]
How to do these in C/C++:

1) multiple platforms: http://stackoverflow.com/questions/1023306/finding-current-executables-path-without-proc-self-exe/1024937#1024937

2) posix: http://stackoverflow.com/questions/504810/how-do-i-find-the-current-machines-full-hostname-in-c-hostname-and-domain-info
Windows: https://msdn.microsoft.com/en-us/library/windows/desktop/ms738527(v=vs.85).aspx

3) posix: http://stackoverflow.com/a/8953466
Windows: http://stackoverflow.com/a/11587467

**Comment by nsoblath** [comment]
1 and 2) These would be necessary to be sure of exactly which executable was used. Therefore I think they make sense. The hostname will tell us what kind of system was being used (e.g. Linux or Windows). The full path will tell us if the official version or a different build was used.

3) I don't know if this is useful for having in the file header in particular, but I agree with Ben's reason for potential user verification.

**Comment by laroque** [comment]
check
